### PR TITLE
Sdxl

### PR DESCRIPTION
**Pull request by FizzleDorf**
PR for sdxl support. Will merge when the testing on the sdxl branch is confirmed working on multiple machines. Modules.json still being worked on.

### CODE REVIEW

**Comment by FizzleDorf** [comment]
for @hlky, use the hashes from the new [huggingface repo](https://huggingface.co/Fizzledorf/AITemplateXL) that has only the new modules. Moving forward we will be using this since it won't require cleanup of the old modules.

**Comment by hlky** [comment]
@FizzleDorf [linux_sm80_bs1.zip](https://modules.diffuse.rs/linux_sm80_bs1.zip)

I've also pushed an update to modules.json, these are added already and the urls will hopefully be valid once uploaded. The old modules are removed

**Comment by hlky** [comment]
There's still controlnet modules to do for Windows and Linux, I'll start those now. Then replacements for sm75, I think it's safe to exclude sm70. The only question is batch sizes to support, and how much higher to go with resolution.

**Comment by FizzleDorf** [comment]
4096 is a good place to cap resolution at for now. We can focus on getting bs1 for both os for now unless you wanted to bulk everything in at once. I'm not sure if we should go bs8 like last time. Thanks for your time and work. I appreciate it.

**Comment by FizzleDorf** [comment]
I'll be able to add the new modules when I return from work so apologies ahead if time for the delay.

**Comment by hlky** [comment]
I've removed the `keep_loaded` option from vae nodes, with the existing code because the vae modules are the same between architectures when switching from say v1 to xl the weights may not be reapplied. The `keep_loaded` option mainly benefits unet, whereas applying vae weights is fast and unloading the module frees the vram.
For unet the weights should apply correctly when the model is changed, and when the module is changed.
Both vae and unet seem ok in my testing

**Comment by hlky** [comment]
[4096.zip](https://modules.diffuse.rs/4096.zip) 4096 modules

and all together, this has all the modules from today and those already on Fizzledorf/AITemplateXL so this one is probably quickest to use now, @FizzleDorf
[modules.zip](https://modules.diffuse.rs/modules.zip)

They're also hosted using the same names at `modules.diffuse.rs` e.g.
`https://huggingface.co/Fizzledorf/AITemplateXL/resolve/main/modules/linux/sm80/bs1/4096/vae_encode_4096.dll.xz` -> `https://modules.diffuse.rs/linux/sm80/bs1/4096/vae_encode_4096.dll.xz`

Btw, the vram figures should be accurate now, they're in mb, and exclude the size of the weights

**Comment by hlky** [comment]
@FizzleDorf I've replaced the domain in modules.json for now so auto-download works and people can start testing easier. The commit can be reverted later if needed.

**Comment by CyberTimon** [comment]
Thank you so much! It finally works on my system. The only problem I have when I use Vae Decode AITemplate it returns a black image. But when I use the normal VAE Decode it works. I'm generating a simple 1024x1024 image.

**Comment by Shaistrong** [comment]
> @FizzleDorf I've replaced the domain in modules.json for now so auto-download works and people can start testing easier. The commit can be reverted later if needed.

Is it fixed for Linux? I know many people who want to use this but have Linux, on windows it works flawlessly though, no need for changing the code or messing with anything.. is it like that on Linux as well as of now?

**Comment by hlky** [comment]
@CyberTimon Use [this vae](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) for sdxl, it is fixed to work in fp16.

@Shaistrong Yes the linux modules are available, the auto-download should now work, and no modifications are required with the latest version of this branch.

**Comment by Shaistrong** [comment]
> @CyberTimon Use [this vae](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) for sdxl, it is fixed to work in fp16.
> 
> @Shaistrong Yes the linux modules are available, the auto-download should now work, and no modifications are required with the latest version of this branch.

I know for a fact it's flawless on windows, I made a workflow that creates extremely high quality SDXL images with AIT in less than 10 seconds. I asked if it's flawlessly automatic on Linux as well.

**Comment by CyberTimon** [comment]
Yeah it works perfectly fine (except for the vae decoding) for me! :)

**Comment by CyberTimon** [comment]
Thank you the vae fix worked!

**Pull request merged**
